### ISSUE TITLE
Huhnitor on phone

### ISSUE THREAD

**Issue by ako-si-haxcoder** [SpacehuhnTech/Huhnitor#26]
I was wondering if huhnitor can be installed on phone or do you have a huhnitor version that supports android phones

This could be useful as some people does not have a laptop to work with.  

Looking forward to your response.

**Comment by the-Jamz** [comment]
Hi, this is an untested scenario; but you could potentially compile it yourself for Android although we don't have a tested binary and even if it does compile, I'm not sure it would work because I have no idea how serial connections are handled over USB on Android. Another possibility is (I think) you could use a different existing Android app to achieve similar functionality; the Huhnitor is just a serial terminal with some features that make life a bit easier, I'm not sure of existing apps that do this so I wont suggest any, but I'm sure you can find a serial monitor/ serial terminal app.

That said, the [WiFi Deauther V2](https://github.com/SpacehuhnTech/esp8266_deauther) (the latest version is v3, but core functionality is the same), has a web UI, and can be accessed on mobile devices. This doesn't require use of the Huhnitor or a different serial monitor program.

Hope this helps.
